### ISSUE TITLE
Simple example of gohcl and interpolation

### ISSUE THREAD

**Issue by tomqwpl** [hashicorp/hcl#496]
Perhaps I'm missing something here. Naively I was trying to parse a document consisting of:
```
name = Tom
message = "Hello, ${name}!"
```
Then decode the result using gohcl into a structure:
```
type test struct {
	Message string `hcl:"message"`
}
var test test
err = gohcl.DecodeBody(file.Body, nil, &test)
```

However, this gives me an error about not knowing what "name" is. I can provide an explicit list of variables to substitute:
```
err = gohcl.DecodeBody(file.Body, &hcl.EvalContext{
	Variables: map[string]cty.Value{
		"name": cty.StringVal("Tom"),
	},
}, &test)
```
This works. However naively I was expecting to be able to resolve variables from other properties within the config file. So what I was hoping to be able to do is roughly the following (forgive expressing this in YAML, I'm not yet familiar with hcl syntax):
```
group1:
    field1: value1
    field2: ${group3.field1}
group2:
    field1: value1
    field2: ${group1.field2}
group3:
    field1: value5
    field2: 5  
```
(Note recursive interpolation group1.field2 references group1.field, which then references group3.field1). I'm trying to work out whether there's the equivalent of that in HCL, and if so how I would do it. I would seem to need to take a Body and then populate a EvalContext from it, that I then pass into DecodeBody. Am I going to have to do that manually, or is there a utility method somewhere I can use?

Thanks.
